name: wfntp
channels:
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.4.26
  - cairo=1.16.0
  - certifi=2022.5.18.1
  - cmake=3.22.1
  - dbus=1.13.18
  - eigen=3.2
  - expat=2.4.4
  - ffmpeg=4.2.2
  - fontconfig=2.13.1
  - freetype=2.11.0
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=2.8.1
  - hdf5=1.10.6
  - icu=58.2
  - jpeg=9e
  - krb5=1.19.2
  - lame=3.100
  - ld_impl_linux-64=2.38
  - libcurl=7.82.0
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libidn2=2.3.2
  - libnghttp2=1.46.0
  - libopenblas=0.3.18
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.14
  - lz4-c=1.9.3
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.16.6
  - numpy-base=1.16.6
  - opencv=4.5.5
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - pcre=8.45
  - pip=21.2.4
  - pixman=0.40.0
  - python=3.9.12
  - qt=5.9.7
  - readline=8.1.2
  - rhash=1.4.1
  - setuptools=61.2.0
  - sqlite=3.38.3
  - tzdata=2022a
  - wheel=0.37.1
  - x264=1!157.20191217
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - mahotas==1.4.12
    - opencv-contrib-python==4.6.0.66
    - opencv-python==3.4.17.61
    - packaging==21.3
    - pandas==1.4.2
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - six==1.16.0
    - tk==0.1.0
    - trackpy==0.5.0
